### ISSUE TITLE
Allow to configure the delimiter (and add "strict" flag)

### ISSUE THREAD

**Issue by gajus** [IonicaBizau/regex-parser.js#10]
Allow to configure the delimiter. e.g.

`/foo/bar` is now being parsed into `/\/foo\/bar/` when it should throw an error:

> Invalid flags supplied to RegExp constructor 'b'

This could be done if is known that the delimiter is `/`.

**Comment by IonicaBizau** [comment]
That's a good point! :+1: Contributions are welcome in this direction!

What do you mean by the `strict` flag?

**Comment by gajus** [comment]
Well, simply defining a delimiter does not necessitate its use.

```js
parse('foo', '/'); // /foo/
parse('/foo/', '/'); // /foo/
parse('/foo/bar', '/'); // error

parse('/foo/', '/', true); // /foo/
parse('foo', '/', true); // error

```

This is just a recommendation.

I am not going to be able to contribute a PR.

**Comment by IonicaBizau** [comment]
Thanks! That looks good!

> I am not going to be able to contribute a PR.

If you need it now, I may do it. If it's not urgent, I'll leave it for later/somebody else. :smile:

**Comment by gajus** [comment]
No urgency.
